#!/bin/bash

sbatch run_cosolvkit_charged_far.sbatch
sbatch run_cosolvkit_charged_halton.sbatch
sbatch run_cosolvkit_charged_random.sbatch
sbatch run_cosolvkit_non_polar_far.sbatch
sbatch run_cosolvkit_non_polar_halton.sbatch
sbatch run_cosolvkit_non_polar_random.sbatch
sbatch run_cosolvkit_polar_far.sbatch
sbatch run_cosolvkit_polar_halton.sbatch
sbatch run_cosolvkit_polar_random.sbatch
